services:
  - type: web
    name: workguard360-backend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        fromSecret: CLIENT_URL
      - key: MONGO_URI
        fromSecret: MONGO_URI
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: JWT_EXPIRE
        value: 30d
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: LOG_LEVEL
        value: info